### PR TITLE
Progression of UML-Final Diagram

### PR DESCRIPTION
**Pull request by edwardrh**
What I have so far for the Final UML Diagram

### CODE REVIEW

**Comment by edwardrh** [comment]
I didn't touch the Hands and Deck class on the diagram yet, which were presented on the Proposal UML Diagram, because I am unsure how to change them.

**Comment by edwardrh** [comment]
Okay, removed Hands and Deck Class with consideration of additional input

**Comment by parkj6** [comment]
awesome. looks good.

**Comment by parkj6** [comment]
this closes #7

**Comment by barrieca** [comment]
Sweet. Abstract player model representation seems on point.

**Pull request merged**
